"""Snowflake logical table DDL for the canonical graph artifact contract."""

from __future__ import annotations

import re

_SCHEMA_INTROSPECTION_DIMENSION = 1536
_CREATE_TABLE_RE = re.compile(
    r"CREATE TABLE IF NOT EXISTS\s+(?P<table>[A-Z][A-Z0-9_]*)\s*\((?P<body>.*)\)\s*\Z",
    re.DOTALL,
)
_COLUMN_DEFINITION_RE = re.compile(r"^\s*(?P<column>[A-Z][A-Z0-9_]*)\s+")


def render_snowflake_schema_sql(embedding_dimension: int) -> str:
    """Render the canonical Snowflake table DDL for a vector dimension."""

    dim = _validate_dimension(embedding_dimension)
    return f"""
CREATE TABLE IF NOT EXISTS KG_JOB (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  STATUS STRING NOT NULL,
  ATTEMPT NUMBER DEFAULT 0,
  LEASE_OWNER STRING,
  LEASE_EXPIRES_AT TIMESTAMP_NTZ,
  CONFIG VARIANT,
  ERROR VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_JOB_FILE (
  ID STRING PRIMARY KEY,
  JOB_ID STRING NOT NULL,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  SOURCE_URI STRING,
  BLOB_PATH STRING,
  CHECKSUM STRING,
  STATUS STRING NOT NULL,
  WORKER_ID STRING,
  LEASE_UNTIL TIMESTAMP_NTZ,
  ATTEMPTS NUMBER DEFAULT 0,
  ROWS_WRITTEN NUMBER,
  ROW_COUNTS VARIANT,
  STAGE STRING,
  OCR_PROVIDER STRING,
  LLM_PROVIDER STRING,
  EMBED_MODEL STRING,
  EMBED_DIM NUMBER,
  AUDIT VARIANT,
  ERROR VARIANT,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_DOCUMENT (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  CHECKSUM STRING NOT NULL,
  SOURCE_URI STRING NOT NULL,
  MIME_TYPE STRING NOT NULL,
  SIZE_BYTES NUMBER,
  OCR_PROVIDER STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_PAGE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER NOT NULL,
  MARKDOWN STRING,
  RAW_TEXT STRING,
  DETECTED_LANGUAGE STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_BLOCK (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER NOT NULL,
  KIND STRING NOT NULL,
  TEXT STRING,
  BBOX ARRAY,
  METADATA VARIANT,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_ASSET (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  KIND STRING NOT NULL,
  PAGE_NUMBER NUMBER,
  URI STRING,
  METADATA VARIANT,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_CHUNK (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER NOT NULL,
  CHUNK_INDEX NUMBER NOT NULL,
  CONTENT STRING NOT NULL,
  START_OFFSET NUMBER NOT NULL,
  END_OFFSET NUMBER NOT NULL,
  TOKEN_COUNT NUMBER NOT NULL,
  CONTENT_HASH STRING NOT NULL,
  SECTION_PATH ARRAY,
  BLOCK_IDS ARRAY,
  ASSET_IDS ARRAY,
  OCR_GENERATION_ID STRING,
  EMBEDDING VECTOR(FLOAT, {dim}),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_NODE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  NORMALIZED_NAME STRING NOT NULL,
  NAME STRING NOT NULL,
  PRIMARY_TYPE STRING NOT NULL,
  TYPES ARRAY,
  DESCRIPTION STRING NOT NULL,
  EMBEDDING VECTOR(FLOAT, {dim}),
  SOURCE_CHUNK_IDS ARRAY,
  DEGREE NUMBER,
  RANK FLOAT,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_EDGE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  SOURCE_NODE_ID STRING NOT NULL,
  TARGET_NODE_ID STRING NOT NULL,
  RELATION_TYPE STRING NOT NULL,
  DESCRIPTION STRING NOT NULL,
  WEIGHT FLOAT NOT NULL,
  SOURCE_FILE_ID STRING NOT NULL,
  SOURCE_CHUNK_IDS ARRAY,
  EMBEDDING VECTOR(FLOAT, {dim}),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_EVIDENCE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  SUBJECT_ID STRING NOT NULL,
  SUBJECT_KIND STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  CHUNK_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER NOT NULL,
  START_OFFSET NUMBER NOT NULL,
  END_OFFSET NUMBER NOT NULL,
  QUOTE STRING NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_ENTITY_SOURCE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  NODE_ID STRING NOT NULL,
  FILE_ID STRING NOT NULL,
  PER_FILE_DESCRIPTION STRING NOT NULL,
  MENTION_COUNT NUMBER NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_COMMUNITY (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  STABLE_KEY STRING NOT NULL,
  LEVEL NUMBER NOT NULL,
  TITLE STRING NOT NULL,
  SUMMARY STRING NOT NULL,
  RATING FLOAT NOT NULL,
  RATING_EXPLANATION STRING,
  MEMBER_NODE_IDS ARRAY,
  SUGGESTED_QUESTIONS ARRAY,
  EMBEDDING VECTOR(FLOAT, {dim}),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_COMMUNITY_FINDING (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  COMMUNITY_ID STRING NOT NULL,
  SUMMARY STRING NOT NULL,
  EXPLANATION STRING NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_RUN_REPORT (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  JOB_ID STRING NOT NULL,
  RUN_ID STRING NOT NULL,
  REPORT VARIANT NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_GRAPH_METRICS (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  JOB_ID STRING NOT NULL,
  RUN_ID STRING NOT NULL,
  METRICS VARIANT NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_EXTRACTION_TRACE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  JOB_ID STRING NOT NULL,
  RUN_ID STRING NOT NULL,
  STEP_INDEX NUMBER NOT NULL,
  STAGE STRING NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_OCR_CACHE (
  ID STRING PRIMARY KEY,
  FILE_ID STRING NOT NULL,
  CHECKSUM STRING NOT NULL,
  OCR_PROVIDER STRING NOT NULL,
  OPTIONS_HASH STRING NOT NULL,
  PARSED_DOCUMENT VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_EXTRACTION_CACHE (
  ID STRING PRIMARY KEY,
  GRAPH_ID STRING NOT NULL,
  CHUNK_BATCH_HASH STRING NOT NULL,
  LLM_PROVIDER STRING NOT NULL,
  MODEL STRING NOT NULL,
  OPTIONS_HASH STRING NOT NULL,
  RESULT VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS KG_BULK_LOAD (
  ID STRING PRIMARY KEY,
  JOB_ID STRING NOT NULL,
  GRAPH_ID STRING NOT NULL,
  STAGE_PREFIX STRING NOT NULL,
  STATUS STRING NOT NULL,
  ROW_COUNTS VARIANT,
  ERROR VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
"""


def split_sql_statements(sql: str) -> list[str]:
    """Split rendered SQL into executable statements."""

    return [statement.strip() for statement in sql.split(";") if statement.strip()]


def snowflake_schema_columns() -> dict[str, tuple[str, ...]]:
    """Return the table/column contract that the rendered setup SQL creates.

    The access checker uses this helper before a production run to verify that
    the active role can see the schema shape the worker expects. Deriving the
    contract from rendered DDL keeps setup SQL, readiness checks, and tests from
    quietly drifting apart as tables evolve.
    """

    columns_by_table: dict[str, tuple[str, ...]] = {}
    sql = render_snowflake_schema_sql(_SCHEMA_INTROSPECTION_DIMENSION)
    for statement in split_sql_statements(sql):
        match = _CREATE_TABLE_RE.fullmatch(statement)
        if not match:
            continue
        table_name = match.group("table")
        columns = tuple(
            column_match.group("column")
            for line in match.group("body").splitlines()
            if (column_match := _COLUMN_DEFINITION_RE.match(line.strip().rstrip(",")))
        )
        columns_by_table[table_name] = columns
    return columns_by_table


def _validate_dimension(value: int) -> int:
    if value <= 0 or value > _MAX_VECTOR_DIMENSION:
        raise ValueError("Snowflake VECTOR dimension must be between 1 and 4096")
    return value


_MAX_VECTOR_DIMENSION = 4096
